[package]
name = "daemon"
version = "3.0.0"
edition = "2021"
repository = "https://github.com/milkydeferwm/pagelistbot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
host = { path = "../../lib/host" }
interface = { path = "../../lib/interface", features = [ "rpc" ] }
async-trait = "0.1"
tokio = { version = "1.19", features = [ "macros", "rt", "rt-multi-thread" ] }
jsonrpsee = { version = "0.16", features = [ "server" ] }

[dev-dependencies]
