[package]
name = "pagelistbot-query"
version = "4.1.0"
edition = "2021"
repository = "https://github.com/milkydeferwm/pagelistbot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ast = { path = "../../lib/ast", features = [ "parse" ] }
clap = { version = ">=4.3.1", features = [ "cargo", "derive" ] }
futures = "0.3"
intorinf = { path = "../../lib/intorinf" }
itertools = ">=0.10"
mwapi = ">=0.5.0"
mwapi_responses = ">=0.3.4" # T338102
mwtitle = ">=0.2.2"
nom = "7.1.3"
owo-colors = "3.5.0"
provider = { path = "../../lib/provider" }
serde = { version = ">=1.0.156", features = [ "derive" ] }
serde_json = ">=1.0"
solver = { path = "../../lib/solver" }
thiserror = "1.0.40"
tokio = { version = ">=1.23.1", features = [ "macros", "rt", "rt-multi-thread", "signal" ] }
trio-result = { path = "../../lib/trioresult" }

[dev-dependencies]

[[bin]]
name = "query"
path = "src/main.rs"
