[package]
name = "pagelistbot-query-executor"
version = "4.1.0"
edition = "2021"
repository = "https://github.com/milkydeferwm/pagelistbot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../../lib/ast", features = [ "parse" ] }
clap = { version = "4.1.8", features = [ "cargo", "derive" ] }
futures = "0.3"
intorinf = { path = "../../lib/intorinf" }
itertools = { version = "0.10", optional = true }
mwapi = "0.4.3"
mwapi_responses = "0.3.2"
mwtitle = "0.2.2"
nom = "7.1.3"
provider = { path = "../../lib/provider" }
serde = { version = "1.0.156", features = [ "derive" ] }
solver = { path = "../../lib/solver", features = [ "tree-future" ] }
tokio = { version = "1.22", features = [ "macros", "rt", "rt-multi-thread", "signal" ] }

[dev-dependencies]

[[bin]]
name = "query"
path = "src/main.rs"
