name: Build Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build windows:
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package pagelistbot
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: target/release/pagelistbot.exe

  build macos:
    runs-on: macOs-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package pagelistbot
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: target/release/pagelistbot
