name: Build Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings -Zon-broken-pipe=kill

jobs:
  build windows:
    runs-on: windows-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --release --workspace
      - uses: actions/upload-artifact@v3
        with:
          name: win
          path: |
            target/release/daemon.exe

  build macos:
    runs-on: macOs-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --release --workspace
      - uses: actions/upload-artifact@v3
        with:
          name: mac
          path: |
            target/release/pagelistbot
