name: Build Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '!.github/workflows/test.yml'
      - 'LICENSE'
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '!.github/workflows/test.yml'
      - 'LICENSE'
      - '**/README.md'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTC_VERSION: nightly-2022-11-15

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests
        run: cargo test --verbose --workspace

  toolforge:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toolforge-bullseye-sssd:latest
      env:
        CARGO_TERM_COLOR: always
        RUSTFLAGS: -D warnings

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install build-essential pkg-config libssl1.1 libssl-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests
        run: cargo test --verbose --workspace
