name: Build Toolforge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toolforge-bullseye-sssd:latest
      env:
        CARGO_TERM_COLOR: always
        RUSTFLAGS: -D warnings

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install build-essential pkg-config libssl1.1 libssl-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release --workspace
      - uses: actions/upload-artifact@v3
        with:
          name: pagelistbot
          path: |
            target/release/pagelistbotd
            target/release/pagelistbot
