name: Build Toolforge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.tools.wmflabs.org/toolforge-bullseye-sssd:latest
      env:
        CARGO_TERM_COLOR: always
        RUSTFLAGS: -D warnings

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install build-essential pkg-config libssl1.1 libssl-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package pagelistbot
      - uses: actions/upload-artifact@v2
        with:
          name: pagelistbot
          path: target/release/pagelistbot
